### ISSUE TITLE
accuracy.update()

### ISSUE THREAD

**Issue by andrea-pilzer** [rensortino/DDP-Tutorial#1]
Thank you for this nice code!
I tried to run it and I found it to have a problem [here](https://github.com/rensortino/DDP-Tutorial/blob/59baa75bdb1a19b1d9beb3e7765d10be6a423f7a/cifar_example_ddp.py#L133).
It is the first time I use the metrics library of PyTorch, it seems to me (but I may be wrong) you should pass the output and the label.
Please correct me if I am wrong. Thanks, Andrea

**Comment by rensortino** [comment]
Hi Andrea, thank you for your feedback, I'm sorry for my late response. 
Yes, you are right, I forgot to include the parameters to the `update()` function.
I'm going to fix it with a PR.
Thanks
